VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Liaison"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

 
Public LIAI As String
Public SECT As String
Public TEINT As String
Public Eppissur As Boolean
Public Flag As Boolean
Public APP As String
Public POS_OUT As String
Public VOI As String
Public REF_CONNECTEUR As String
Public Eppissur2 As Boolean
Public App2 As String
Public POS_OUT2 As String
Public VOI2 As String
Public REF_CONNECTEUR2 As String
Public Fil As String
