function vbMouseOver(i)
	if i = 0 then
		tr0.style.backgroundcolor = "navy"
		sp0.style.color = "white"
	elseif i = 1 then
		tr1.style.backgroundcolor = "navy"
		sp1.style.color = "white"
	elseif i = 2 then
		tr2.style.backgroundcolor = "navy"
		sp2.style.color = "white"
	elseif i = 3 then
		tr3.style.backgroundcolor = "navy"
		sp3.style.color = "white"
	elseif i = 4 then
		tr4.style.backgroundcolor = "navy"
		sp4.style.color = "white"
	elseif i = 5 then
		tr5.style.backgroundcolor = "navy"
		sp5.style.color = "white"
	elseif i = 6 then
		tr6.style.backgroundcolor = "navy"
		sp6.style.color = "white"
	elseif i = 7 then
		tr7.style.backgroundcolor = "navy"
		sp7.style.color = "white"
	elseif i = 8 then
		tr8.style.backgroundcolor = "navy"
		sp8.style.color = "white"
	elseif i = 9 then
		tr9.style.backgroundcolor = "navy"
		sp9.style.color = "white"
	elseif i = 10 then
		tr10.style.backgroundcolor = "navy"
		sp10.style.color = "white"
	elseif i = 11 then
		tr11.style.backgroundcolor = "navy"
		sp11.style.color = "white"
	elseif i = 12 then
		tr12.style.backgroundcolor = "navy"
		sp12.style.color = "white"
	elseif i = 13 then
		tr13.style.backgroundcolor = "navy"
		sp13.style.color = "white"
	elseif i = 14 then
		tr14.style.backgroundcolor = "navy"
		sp14.style.color = "white"
	elseif i = 15 then
		tr15.style.backgroundcolor = "navy"
		sp15.style.color = "white"
	elseif i = 16 then
		tr16.style.backgroundcolor = "navy"
		sp16.style.color = "white"
	elseif i = 17 then
		tr17.style.backgroundcolor = "navy"
		sp17.style.color = "white"
	end if
end function
function vbMouseOut(i)
	if i = 0 then
		tr0.style.backgroundcolor = "white"
		sp0.style.color = "navy"
	elseif i = 1 then
		tr1.style.backgroundcolor = "white"
		sp1.style.color = "navy"
	elseif i = 2 then
		tr2.style.backgroundcolor = "white"
		sp2.style.color = "navy"
	elseif i = 3 then
		tr3.style.backgroundcolor = "white"
		sp3.style.color = "navy"
	elseif i = 4 then
		tr4.style.backgroundcolor = "white"
		sp4.style.color = "navy"
	elseif i = 5 then
		tr5.style.backgroundcolor = "white"
		sp5.style.color = "navy"
	elseif i = 6 then
		tr6.style.backgroundcolor = "white"
		sp6.style.color = "navy"
	elseif i = 7 then
		tr7.style.backgroundcolor = "white"
		sp7.style.color = "navy"
	elseif i = 8 then
		tr8.style.backgroundcolor = "white"
		sp8.style.color = "navy"
	elseif i = 9 then
		tr9.style.backgroundcolor = "white"
		sp9.style.color = "navy"
	elseif i = 10 then
		tr10.style.backgroundcolor = "white"
		sp10.style.color = "navy"
	elseif i = 11 then
		tr11.style.backgroundcolor = "white"
		sp11.style.color = "navy"
	elseif i = 12 then
		tr12.style.backgroundcolor = "white"
		sp12.style.color = "navy"
	elseif i = 13 then
		tr13.style.backgroundcolor = "white"
		sp13.style.color = "navy"
	elseif i = 14 then
		tr14.style.backgroundcolor = "white"
		sp14.style.color = "navy"
	elseif i = 15 then
		tr15.style.backgroundcolor = "white"
		sp15.style.color = "navy"
	elseif i = 16 then
		tr16.style.backgroundcolor = "white"
		sp16.style.color = "navy"
	elseif i = 17 then
		tr17.style.backgroundcolor = "white"
		sp17.style.color = "navy"
	end if
end function
