VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "classTor"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

  
Public NewBlock   As Collection
Public Attribues As Collection
Public TableauFiles As New Collection
Public InsertPoint  As New Collection
Public XScaleFactor As New Collection
Public YScaleFactor As New Collection
Public ZScaleFactor As New Collection
Public Rotation As New Collection
Public PosOk As New Collection
Public Existe As New Collection

Public NewBlockT   As Collection
Public AttribuesT As Collection
Public TableauFilesT As New Collection
Public InsertPointT  As New Collection
Public XScaleFactorT As New Collection
Public YScaleFactorT As New Collection
Public ZScaleFactorT As New Collection
Public RotationT As New Collection
Public PosOkT As New Collection
Public ExisteT As New Collection
